### ISSUE TITLE
Custom component now working for my PRT-N stats with built-in and remote sensors

### ISSUE THREAD

**Issue by NigelCoxon** [bretttickx/HA-heatmiser-component#1]
Hi Brett

Thanks for setting up this custom component. With a few tweaks, it is now working well with my heatmiser setup of
12 x PRT-N v3 with builtin sensors
3   x PRT-N v3 with remote air sensors

In its original form, it correctly reported the target temps, and the current temps of the builtin sensor stats. However, the remote air sensor stats were all reporting 52 C regardless of actual temp!
Looking at the code, I could see it was picking up the wrong field which was set to 0xff or 511 decimal. This resulted in 52 once scaled by 10 and "ceilinged". I also noticed the code was only picking up a 1 byte value, (as did the original component). This works fine for values  up to 51 degrees, so would be unlikely to be discovered if using centigrade, but would be uncovered if using fahrenheit.

So on my HA pi, I changed the routine "current_temperature" in climate.py in the custom component as this txt file
[snip.txt](https://github.com/bretttickx/HA-heatmiser-component/files/5597484/snip.txt)

I also removed import math form the top

This works well for all my stats. To test further, I changed a couple of stats to report in fahrenheit, and this also works fine.
I don't have any stats with remote floor sensors, so couldnt test this.

If I knew how to use Github properly, I could have sorted out a pull request, but I'm afraid this is still on my todo list.

It would be great if the official component could be updated too

Regards
Nigel

**Comment by bretttickx** [comment]
@NigelCoxon, nice one!  Once Andy has passed ownership over to the main [heatmiserV3](https://github.com/andylockran/heatmiserV3) repo, i can make these changes then look at getting the Hass component updated.
I take it you have a UFH system? what are the outside temp sensor doing to the stats? changing the target temps inside?
Cheers
Brett

**Comment by bretttickx** [comment]
updated repo thanks again ;-)

**Comment by NigelCoxon** [comment]
Thanks for taking on getting this into the main Hass component

Yes I have a UFH system, powered by a ground source heat pump, with Heatmiser stats. the stats with remote air sensors are used in my bathrooms, where the stat is just outside the room and the sensor is inside the room. This stops the stat being exposed to high humidity. I think the floor sensor in the heatmiser stats are an optional extra, and are used for electric floor heating to avoid overheating the floor if the room temperature has not been satisfied. My heat pump works at a max of 35C, so I dont use any floor sensors.
